# -*- coding: utf-8 -*-
"""Minimal sound-effects layer for the race modes (single / multiplayer / camp).

Design notes:
  * Sounds are loaded lazily and ALL failures are swallowed: a machine with no
    audio device (or a missing Sounds/ folder) plays silently instead of
    crashing the game. AI Evolution never imports this module.
  * The WAVs in Sounds/ are generated by `generate_sounds.py`; if they are
    missing they are regenerated on the fly.
  * Everything here is a one-shot (countdown cues, starter, explosion);
    there is no continuous driving-loop bed.
"""
import os

import pygame

_ENABLED = True
_READY = False          # have we tried (successfully or not) to init the mixer?
_AVAILABLE = False
_SOUNDS = {}

_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "Sounds")
_ALL = ("ready", "go", "crash", "engine_start", "victory")
# crash is deliberately the loudest thing in the game; the win sting sits just
# below it so a finish is celebrated without drowning the explosion.
_VOLUMES = {"ready": 0.55, "go": 0.85, "crash": 0.85,
            "engine_start": 0.35, "victory": 0.55}

_crash_ch = None
_CHANNELS = {}                 # one-shot name -> Channel it is playing on


def _ensure_assets():
    if all(os.path.exists(os.path.join(_DIR, f"{n}.wav")) for n in _ALL):
        return
    try:
        import generate_sounds
        os.makedirs(_DIR, exist_ok=True)
        for name, fn in generate_sounds.SPECS:
            generate_sounds.write_wav(name, fn())
    except Exception:
        pass                                   # still fine: play() no-ops


def init():
    """Call once after pygame.init(). Safe to call more than once."""
    global _READY, _AVAILABLE, _SOUNDS
    if _READY:
        return _AVAILABLE
    _READY = True
    try:
        if not pygame.mixer.get_init():
            pygame.mixer.init()
        _AVAILABLE = bool(pygame.mixer.get_init())
    except Exception:
        _AVAILABLE = False
        return False

    _ensure_assets()
    for key in _ALL:
        path = os.path.join(_DIR, f"{key}.wav")
        try:
            snd = pygame.mixer.Sound(path)
            snd.set_volume(_VOLUMES[key])
            _SOUNDS[key] = snd
        except Exception:
            pass
    return _AVAILABLE


def _crash_channel():
    """A reserved channel (counting from the end) that auto-play never picks.

    The explosion owns this lane, so it can never be dropped for want of a
    free channel -- it is the one sound that must always be heard.
    """
    global _crash_ch
    if _crash_ch is None:
        try:
            n = max(2, pygame.mixer.get_num_channels())
            _crash_ch = pygame.mixer.Channel(n - 1)
        except Exception:
            _crash_ch = False
    return _crash_ch or None


def _stop_oneshot(name):
    """Cut a still-running one-shot (used to kill the starter on a crash).

    Guarded by `get_sound()`: a Channel object can be recycled for a different
    sound, and we must never mute something that is no longer ours.
    """
    ch = _CHANNELS.pop(name, None)
    snd = _SOUNDS.get(name)
    if ch is None or snd is None:
        return
    try:
        if ch.get_sound() is snd:
            ch.stop()
    except Exception:
        pass


def play(name):
    """Fire-and-forget. Never raises, never blocks."""
    if not _ENABLED or not _AVAILABLE:
        return
    if name == "crash":
        # The explosion always wins: cut the starter mid-rev so nothing rings
        # on underneath the blast.
        _stop_oneshot("engine_start")
    elif name == "victory":
        # The race is over, so the starter has nothing left to announce.
        _stop_oneshot("engine_start")
    snd = _SOUNDS.get(name)
    if snd is None:
        return
    try:
        if name == "crash" and _crash_channel() is not None:
            _crash_channel().play(snd)             # reserved lane for the blast
        else:
            ch = snd.play()
            if ch is not None:
                _CHANNELS[name] = ch               # so it can be cut short
    except Exception:
        pass


def ignite():
    """Fire the engine starter (called when the race goes green)."""
    play("engine_start")


def stop_all():
    """Cut everything still ringing (used when leaving a race mode)."""
    _stop_oneshot("engine_start")
    _stop_oneshot("crash")


def toggle():
    """Mute/unmute. Returns the new state."""
    global _ENABLED
    _ENABLED = not _ENABLED
    return _ENABLED


def is_enabled():
    return _ENABLED


def is_available():
    return _AVAILABLE
